-- MySQL Script generated by MySQL Workbench
-- Sat Jun  1 20:14:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Comercio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Comercio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Comercio` DEFAULT CHARACTER SET utf8 ;
USE `DB_Comercio` ;

-- -----------------------------------------------------
-- Table `DB_Comercio`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Comercio`.`Cliente` (
  `codcli` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(145) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`codcli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Comercio`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Comercio`.`Produto` (
  `codprod` INT NOT NULL AUTO_INCREMENT,
  `DescProd` VARCHAR(145) NOT NULL,
  `codfor` INT NOT NULL,
  `Datacad` DATE NOT NULL,
  PRIMARY KEY (`codprod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Comercio`.`FormaPag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Comercio`.`FormaPag` (
  `codforma` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`codforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Comercio`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Comercio`.`Pedido` (
  `numped` INT NOT NULL AUTO_INCREMENT,
  `DatPed` DATE NOT NULL,
  `codcli` INT NOT NULL,
  `codprod` INT NOT NULL,
  `quant` INT NOT NULL,
  `valuni` FLOAT NOT NULL,
  `codforpag` INT NOT NULL,
  PRIMARY KEY (`numped`),
  INDEX `FK_cliente_ID_idx` (`codcli` ASC) VISIBLE,
  INDEX `FK_Produto_ID_idx` (`codprod` ASC) VISIBLE,
  INDEX `FK_Forpag_ID_idx` (`codforpag` ASC) VISIBLE,
  CONSTRAINT `FK_cliente_ID`
    FOREIGN KEY (`codcli`)
    REFERENCES `DB_Comercio`.`Cliente` (`codcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Produto_ID`
    FOREIGN KEY (`codprod`)
    REFERENCES `DB_Comercio`.`Produto` (`codprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Forpag_ID`
    FOREIGN KEY (`codforpag`)
    REFERENCES `DB_Comercio`.`FormaPag` (`codforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Comercio`.`Fluxo_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Comercio`.`Fluxo_caixa` (
  `codfluxo` INT NOT NULL AUTO_INCREMENT,
  `DatAbe` DATE NOT NULL,
  `numPed` INT NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `dataFec` DATE NOT NULL,
  `Flcaixa` CHAR NOT NULL,
  PRIMARY KEY (`codfluxo`),
  INDEX `FK_pedido_ID_idx` (`numPed` ASC) VISIBLE,
  CONSTRAINT `FK_pedido_ID`
    FOREIGN KEY (`numPed`)
    REFERENCES `DB_Comercio`.`Pedido` (`numped`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;